export enum RegionEnum {
  CHERKASY = 'Cherkasy',
  CHERNIHIV = 'Chernihiv',
  CHERNIVTSI = 'Chernivtsi',
  DNIPRO = 'Dnipro',
  DONETSK = 'Donetsk',
  IVANO_FRANKIVSK = 'Ivano-Frankivsk',
  KHARKIV = 'Kharkiv',
  KHERSON = 'Kherson',
  KHMELNYTSKYI = 'Khmelnytskyi',
  KYIV = 'Kyiv',
  KIROVOHRAD = 'Kirovohrad',
  LUHANSK = 'Luhansk',
  LVIV = 'Lviv',
  MYKOLAIV = 'Mykolaiv',
  ODESA = 'Odesa',
  POLTAVA = 'Poltava',
  RIVNE = 'Rivne',
  SUMY = 'Sumy',
  TERNOPIL = 'Ternopil',
  VINNYTSIA = 'Vinnytsia',
  VOLYN = 'Volyn',
  ZAKARPATTIA = 'Zakarpattia',
  ZAPORIZHZHIA = 'Zaporizhzhia',
  ZHYTOMYR = 'Zhytomyr',
  KRYM = 'Krym',
  UNSPECIFIED = 'Unspecified',
}
